### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by jdbranham** [grafana/simple-react-panel#2]
I'm new to React development, so I could be making a noob mistake, but I get this error when checking out a fresh copy of the master branch and running `yarn build`.  

**Cannot read property 'name' of null**  
```
$ node -v
v8.11.4  

$ npm -v
6.9.0
```

Full output - 
```
$ yarn build
yarn run v1.17.3
$ grafana-toolkit plugin:build
Running Build plugin task
√ Cleaning
√ Preparing
√ Prettier check
√ Linting
 PASS  src/module.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.841s, estimated 2s
Ran all test suites with tests matching "".
√ Running tests
× Cannot read property 'name' of null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by jdbranham** [comment]
I updated Node and Npm but still get the error - 
```
$ node -v
v10.16.0

$ npm -v
6.10.2
```

**Comment by ryantxu** [comment]
@jdbranham -- can you tell me anything else about your environment?  This is what I see:

![image](https://user-images.githubusercontent.com/705951/62100451-a065ed00-b246-11e9-8d12-adc576033f93.png)

**Comment by jdbranham** [comment]
It seems to be Windows specific; I'm able to build in a Linux shell - 
Probably a path separator problem somewhere...

![image](https://user-images.githubusercontent.com/2660839/62102479-c39c9680-b25e-11e9-8b6d-59b3001b9584.png)

**Comment by jdbranham** [comment]
@ryantxu - unrelated question... which OS/shell are you running? I like the git branch indicator in your prompt.

**Comment by ryantxu** [comment]
I'll try to test it better on windows -- yes, most likely a path separator issue with the new `@grafana/toolkit` this is using

**Comment by glindsay78** [comment]
Yeah the problem is in the grafana\toolkit\src\config\webpack.plugin.config.js file line 55
`var idx = id.indexOf('/src/');`

so a local workaround to make it work in windows would be to change it to:
`var idx = id.indexOf('\\src\\');`

![image](https://user-images.githubusercontent.com/16040076/62106802-80d3d080-b2e9-11e9-9049-a7efec25f4b1.png)

**Comment by ryantxu** [comment]
See https://github.com/grafana/grafana/issues/18294

**Comment by ryantxu** [comment]
@jdbranham -- can you pull from master and try again?  toolkit 6.4.0-alpha.42 should work on windows

**Comment by jdbranham** [comment]
Yep - works now!
