### ISSUE TITLE
Can't seem to load the plugin in grafana

### ISSUE THREAD

**Issue by mnik17** [grafana/simple-react-panel#3]
Hi, 

first of all I'm a beginner, so sorry if I'm asking something obvious.

I downloaded the master grafana branch and the master branch of this plugin. Then I ran yarn build and yarn dev, as written in the readme, but when I try loading it in a grafana panel, I get a "panel not found errro", although I see the icon image and the option to use it as visualization. Any ideas?

**Comment by ryantxu** [comment]
@mnik17 -- are you running on windows?  If so, can you update and try again?

If not, can you give me more information and reopen the issue?  In particular what does the chrome console log say?
