### ISSUE TITLE
 Error loading: myorgid-simple-panel

### ISSUE THREAD

**Issue by karlie93** [grafana/simple-react-panel#8]
I read the grafana documentation and starting with this example and then working my way towards integrating the funnel part but I can't seem to get it working。I restarted the Server when I tried opening this Panel I got an error saying Error loading: myorgid-simple-panel.My grafana version is 6.4.4, node.js version is 12.13.1;How to solve this?

**Comment by karlie93** [comment]
My development environment is Windows x64

**Comment by sbelondr** [comment]
Hello,Try npm install before yarn build

**Comment by manu2194** [comment]
I have the same error. 
This is what I found in the browser console:

```
backend.js:6 Error loading panel plugin: myorgid-simple-panel TypeError: r.PanelPlugin is not a constructor
    at Module.eval (module.js:1)
    at n (module.js:1)
    at eval (module.js:1)
    at eval (module.js:1)
    at i (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4
```

**Comment by sbelondr** [comment]
Ok, I think you have a problem because you don't have the latest version.
Therefore `git pull` and try again

**Comment by manu2194** [comment]
> Ok, I think you have a problem because you don't have the latest version.
> Therefore `git pull` and try again

Hi Samuel, 

I've pulled the latest version and it's still not working. 
Still the same Grafana error, and the same console error. 
Have you tried building and running it on Grafana?

**Comment by sbelondr** [comment]
Yes but I'm on Linux.
You have the same mistake here: https://github.com/grafana/grafana/issues/20338
And the last simple-react-panel pull repair that: https://github.com/grafana/simple-react-panel/commit/ca7f48c685aa94c40eeabf63efbdf5eebe6baa14 (in src/SimplePanel.tsx and src/SimpleEditor.tsx)

Did you install Grafana from the sources?

**Comment by manu2194** [comment]
> Yes but I'm on Linux.
> You have the same mistake here: [grafana/grafana#20338](https://github.com/grafana/grafana/issues/20338)
> And the last simple-react-panel pull repair that: [ca7f48c](https://github.com/grafana/simple-react-panel/commit/ca7f48c685aa94c40eeabf63efbdf5eebe6baa14) (in src/SimplePanel.tsx and src/SimpleEditor.tsx)
> 
> Did you install Grafana from the sources?

I'm on the MacOS. 
All my files look exactly like how it is in that repair. The "fixes" that the person in the thread you posted were already implemented by me in my files 

I installed Grafana through homebrew.

**Comment by manu2194** [comment]
I just got it working. PanelPlugin should be imported from @grafana/ui and not @grafana/data

My old module.ts looked like 
```
import { PanelPlugin } from '@grafana/data';
import { SimpleOptions, defaults } from './types';
import { SimplePanel } from './SimplePanel';
import { SimpleEditor } from './SimpleEditor';

export const plugin = new PanelPlugin<SimpleOptions>(SimplePanel).setDefaults(defaults).setEditor(SimpleEditor);
```
My new module.ts looks the same, but with the first line replaced to 
```
import { PanelPlugin } from '@grafana/ui' 
```

**Comment by efvhi** [comment]
> I just got it working. PanelPlugin should be imported from @grafana/ui and not @grafana/data
> 
> My old module.ts looked like
> 
> ```
> import { PanelPlugin } from '@grafana/data';
> import { SimpleOptions, defaults } from './types';
> import { SimplePanel } from './SimplePanel';
> import { SimpleEditor } from './SimpleEditor';
> 
> export const plugin = new PanelPlugin<SimpleOptions>(SimplePanel).setDefaults(defaults).setEditor(SimpleEditor);
> ```
> 
> My new module.ts looks the same, but with the first line replaced to
> 
> ```
> import { PanelPlugin } from '@grafana/ui' 
> ```



> I just got it working. PanelPlugin should be imported from @grafana/ui and not @grafana/data
> 
> My old module.ts looked like
> 
> ```
> import { PanelPlugin } from '@grafana/data';
> import { SimpleOptions, defaults } from './types';
> import { SimplePanel } from './SimplePanel';
> import { SimpleEditor } from './SimpleEditor';
> 
> export const plugin = new PanelPlugin<SimpleOptions>(SimplePanel).setDefaults(defaults).setEditor(SimpleEditor);
> ```
> 
> My new module.ts looks the same, but with the first line replaced to
> 
> ```
> import { PanelPlugin } from '@grafana/ui' 
> ```

 Module '"../node_modules/@grafana/ui"' has no exported member 'PanelPlugin'.

??

**Comment by karlie93** [comment]
> I just got it working. PanelPlugin should be imported from @grafana/ui and not @grafana/data
> 
> My old module.ts looked like
> 
> ```
> import { PanelPlugin } from '@grafana/data';
> import { SimpleOptions, defaults } from './types';
> import { SimplePanel } from './SimplePanel';
> import { SimpleEditor } from './SimpleEditor';
> 
> export const plugin = new PanelPlugin<SimpleOptions>(SimplePanel).setDefaults(defaults).setEditor(SimpleEditor);
> ```
> 
> My new module.ts looks the same, but with the first line replaced to
> 
> ```
> import { PanelPlugin } from '@grafana/ui' 
> ```

I modified the mudule.ts according to your way,it still not working, I input 'yarn dev',got an error "/@grafana/ui"' has no exported member 'PanelPlugin'."

**Comment by manu2194** [comment]
Sorry guys. I forgot to share my full `module.ts` file. 

You need to add `// @ts-ignore` on the first line of your `module.ts` file. 
So the final version looks like:

```
// @ts-ignore
import { PanelPlugin } from '@grafana/ui';
import { SimpleOptions, defaults } from './types';
import { SimplePanel } from './SimplePanel';
import { SimpleEditor } from './SimpleEditor';

export const plugin = new PanelPlugin<SimpleOptions>(SimplePanel).setDefaults(defaults).setEditor(SimpleEditor);
```

That should solve your problem. 
Don't ask me why that works though.

**Comment by speg** [comment]
I also can't get this to work.

The plugin shows up in the panel list by clicking on it gives the `error loading: myorgid-simple-pane`

the console complains:
```
keybindingSrv.ts:20 Error loading panel plugin: myorygid-simple-panel SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at st (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4
```

**Comment by efvhi** [comment]
i solved the problem by upgrading grafana to 6.5.x .

**Comment by gretamosa** [comment]
In any case, there is a lot of mismatches between alpha plugins (i.e. piechart alpha panel) in Grafana core and this template. I think it would be reviewed and to propose an unified usage of @grafana libraries.

**Comment by ryantxu** [comment]
if this still exists... post again -- my guess is the plugin was not built
